[[Readline]]
arch = "x86_64"
git-tree-sha1 = "d10e74bbf6d3e918ccb803ae80b257391e6a3a9f"
libc = "glibc"
os = "linux"

    [[Readline.download]]
    sha256 = "744af4762d083ffd3139534038c6dec046e1ba3f8ef4c2946f80a1f2a4ac10a4"
    url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v8.3.0-GCCBootstrap-x86_64-linux-gnu/Readline-v8.3.0-x86_64-linux-gnu.tar.gz"

[[Readline-build_log]]
arch = "x86_64"
git-tree-sha1 = "dc6834662814faaaf7e574bf706a25e4c5ce3b60"
lazy = true
libc = "glibc"
os = "linux"

    [[Readline-build_log.download]]
    sha256 = "cc39eb6964c6dc7901157b509d311dfac335550acb4caa6e4a723b155b155b95"
    url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v8.3.0-GCCBootstrap-x86_64-linux-gnu/Readline-build_log-v8.3.0-x86_64-linux-gnu.tar.gz"

[[Readline-extract_log]]
arch = "x86_64"
git-tree-sha1 = "fcb427b8e29b7a78abe572e859ab182dd121c0e1"
lazy = true
libc = "glibc"
os = "linux"

    [[Readline-extract_log.download]]
    sha256 = "e01ff60fd77b3ccdb0dc356e5026998f0791110cecddd75246332e0431e39728"
    url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v8.3.0-GCCBootstrap-x86_64-linux-gnu/Readline-extract_log-v8.3.0-x86_64-linux-gnu.tar.gz"
