[[Readline]]
arch = "x86_64"
git-tree-sha1 = "d10e74bbf6d3e918ccb803ae80b257391e6a3a9f"
libc = "glibc"
os = "linux"

    [[Readline.download]]
    sha256 = "121e12a2561036a6b266b1a10cb5683b0b5523639da869c97615a6190d679eb1"
    url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v8.3.0-GCCBootstrap-x86_64-linux-gnu/Readline-v8.3.0-x86_64-linux-gnu.tar.gz"

[[Readline-build_log]]
arch = "x86_64"
git-tree-sha1 = "befc0cfa06b3ebde99d6147397bc39ef25878c81"
lazy = true
libc = "glibc"
os = "linux"

    [[Readline-build_log.download]]
    sha256 = "dc3933cf64df481ffe940215ccf533e71192babdfe599b800a627a4f2e015fb0"
    url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v8.3.0-GCCBootstrap-x86_64-linux-gnu/Readline-build_log-v8.3.0-x86_64-linux-gnu.tar.gz"

[[Readline-extract_log]]
arch = "x86_64"
git-tree-sha1 = "ead7c2a9770662d750143731ebc7791943f55dd4"
lazy = true
libc = "glibc"
os = "linux"

    [[Readline-extract_log.download]]
    sha256 = "2febd9159bcb95afa24136c099f53b97955549dd11d6f3d1a90dfe0f372c3c55"
    url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v8.3.0-GCCBootstrap-x86_64-linux-gnu/Readline-extract_log-v8.3.0-x86_64-linux-gnu.tar.gz"
