[[Readline]]
arch = "x86_64"
git-tree-sha1 = "d10e74bbf6d3e918ccb803ae80b257391e6a3a9f"
libc = "glibc"
os = "linux"

    [[Readline.download]]
    sha256 = "c02cade8c682f2469b98590529225358e76bb9602d920b5268083e76b995110c"
    url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v8.3.0-GCCBootstrap-x86_64-linux-gnu/Readline-v8.3.0-x86_64-linux-gnu.tar.gz"

[[Readline-build_log]]
arch = "x86_64"
git-tree-sha1 = "9b6bbf9f9a9622bbcdeb1760860c830e046167bf"
lazy = true
libc = "glibc"
os = "linux"

    [[Readline-build_log.download]]
    sha256 = "e618b96851e25f8bab59b06a8872b55fba710e3b3ff8187eec84bdccac9e72c2"
    url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v8.3.0-GCCBootstrap-x86_64-linux-gnu/Readline-build_log-v8.3.0-x86_64-linux-gnu.tar.gz"

[[Readline-extract_log]]
arch = "x86_64"
git-tree-sha1 = "6ae536fd5727959276ab2c8f66101f7d964f7f13"
lazy = true
libc = "glibc"
os = "linux"

    [[Readline-extract_log.download]]
    sha256 = "dbbe7a77b5b6302db170ae08d4343fac3f9b2aaf4262780ff6d6032a8b16d793"
    url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v8.3.0-GCCBootstrap-x86_64-linux-gnu/Readline-extract_log-v8.3.0-x86_64-linux-gnu.tar.gz"
