[[Readline]]
arch = "x86_64"
git-tree-sha1 = "d10e74bbf6d3e918ccb803ae80b257391e6a3a9f"
libc = "glibc"
os = "linux"

    [[Readline.download]]
    sha256 = "a2a40fd785f081c7668902d56d6c17ee48319bf1765d9c49dfb75057294a04df"
    url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v8.3.0-GCCBootstrap-x86_64-linux-gnu/Readline-v8.3.0-x86_64-linux-gnu.tar.gz"

[[Readline-build_log]]
arch = "x86_64"
git-tree-sha1 = "eaccf552ac6e32b49ac7f81b67ed77eb3f2c031f"
lazy = true
libc = "glibc"
os = "linux"

    [[Readline-build_log.download]]
    sha256 = "c1f54e5c5f5aa27f061e8f8bb3498ee6accdde68d12a72794f99944f2ec0dc57"
    url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v8.3.0-GCCBootstrap-x86_64-linux-gnu/Readline-build_log-v8.3.0-x86_64-linux-gnu.tar.gz"

[[Readline-extract_log]]
arch = "x86_64"
git-tree-sha1 = "601a9979b487f599f546b88ad2273855f98370b9"
lazy = true
libc = "glibc"
os = "linux"

    [[Readline-extract_log.download]]
    sha256 = "1f9991c414c3f89801c922b48ff6730237c2f2d9159adad03e16d03baee694f3"
    url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v8.3.0-GCCBootstrap-x86_64-linux-gnu/Readline-extract_log-v8.3.0-x86_64-linux-gnu.tar.gz"
